### ISSUE TITLE
Style inside html tag

### ISSUE THREAD

**Issue by VadimsMalickis** [KIvanovs/vizitkakarta#1]
https://github.com/KIvanovs/vizitkakarta/blob/c3daa24307988f99320ecde15230819bbd7b1bc0/index.html#L16-L20

Style atributus iekš html tag mēs nelietojam, lūgums visus stilus pārnest uz css failiem.

**Comment by VadimsMalickis** [comment]
@KIvanovs redzu kā Jums patīk labot README failu, bet Jums ir reāla problēma, kura bija noradīta augstāk.

**Comment by KIvanovs** [comment]
@VadimsMalickis Es šo kļūdu izlaboju jau sen. Par README failu, GitHub Pages neiedeva pareizo linku, mēģināju to izdarīt manuāli, + manā datorā bija problēmas ar git push un git pull, tāpēc man jāizdzēst manuāli visus failus un tos aizstāt.
